repos:
-   repo: https://github.com/ambv/black
    rev: 23.10.0
    hooks:
    - id: black
      language_version: python3.11
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    - id: end-of-file-fixer
      exclude: '.bumpversion.cfg'
    - id: trailing-whitespace
      exclude: '.bumpversion.cfg'
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.1.1"
    hooks:
    - id: ruff
      args: ["--fix"]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.6.1"
    hooks:
    - id: mypy
